version: 2

jobs:
  build:
    working_directory: ~/CryptoMoon
    docker:
      - image: circleci/android:api-26-alpha
    steps:
      - checkout
      - run:
          name: Configure Android Licences
          command: |
            mkdir "${ANDROID_HOME}/licenses" || true
            echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "${ANDROID_HOME}/licenses/android-sdk-license"
            echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "${ANDROID_HOME}/licenses/android-sdk-license"
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew --no-daemon --stacktrace androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Android build
          command: ./gradlew --no-daemon --stacktrace assemble check
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs
          destination: outputs
      - store_test_results:
          path: app/build/test-results